localhost:
  hostname: localhost
  user: root
  port: 2222
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/dep_id_rsa
#  forwardAgent: true
#  multiplexing: true
#  sshOptions:
 #   UserKnownHostsFile: /dev/null
 #   StrictHostKeyChecking: no
  stage: development
 # roles:
 #   - app
 #   - db
  deploy_path: /_DEPLOYER_TEST
# extra_param: "foo {{hostname}}"